# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/guessing-game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/guessing-game.proto\"\x17\n\x05Guess\x12\x0e\n\x06number\x18\x01 \x01(\x05\"+\n\x0bGuessResult\x12\x1c\n\x06result\x18\x01 \x01(\x0e\x32\x0c.GuessStatus*W\n\x0bGuessStatus\x12\x0e\n\nGUESS_NONE\x10\x00\x12\x11\n\rGUESS_TOO_LOW\x10\x01\x12\x12\n\x0eGUESS_TOO_HIGH\x10\x02\x12\x11\n\rGUESS_CORRECT\x10\x03\x32\x33\n\x0cGuessingGame\x12#\n\tMakeGuess\x12\x06.Guess\x1a\x0c.GuessResult\"\x00\x42\x0bZ\tpkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.guessing_game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\tpkg/proto'
  _globals['_GUESSSTATUS']._serialized_start=99
  _globals['_GUESSSTATUS']._serialized_end=186
  _globals['_GUESS']._serialized_start=29
  _globals['_GUESS']._serialized_end=52
  _globals['_GUESSRESULT']._serialized_start=54
  _globals['_GUESSRESULT']._serialized_end=97
  _globals['_GUESSINGGAME']._serialized_start=188
  _globals['_GUESSINGGAME']._serialized_end=239
# @@protoc_insertion_point(module_scope)
