# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import guessing_game_pb2 as proto_dot_guessing__game__pb2


class GuessingGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeGuess = channel.unary_unary(
                '/GuessingGame/MakeGuess',
                request_serializer=proto_dot_guessing__game__pb2.Guess.SerializeToString,
                response_deserializer=proto_dot_guessing__game__pb2.GuessResult.FromString,
                )


class GuessingGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeGuess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuessingGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeGuess': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeGuess,
                    request_deserializer=proto_dot_guessing__game__pb2.Guess.FromString,
                    response_serializer=proto_dot_guessing__game__pb2.GuessResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GuessingGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GuessingGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeGuess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GuessingGame/MakeGuess',
            proto_dot_guessing__game__pb2.Guess.SerializeToString,
            proto_dot_guessing__game__pb2.GuessResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
