// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/guessing-game.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GuessingGameClient is the client API for GuessingGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuessingGameClient interface {
	MakeGuess(ctx context.Context, in *Guess, opts ...grpc.CallOption) (*GuessResult, error)
}

type guessingGameClient struct {
	cc grpc.ClientConnInterface
}

func NewGuessingGameClient(cc grpc.ClientConnInterface) GuessingGameClient {
	return &guessingGameClient{cc}
}

func (c *guessingGameClient) MakeGuess(ctx context.Context, in *Guess, opts ...grpc.CallOption) (*GuessResult, error) {
	out := new(GuessResult)
	err := c.cc.Invoke(ctx, "/GuessingGame/MakeGuess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuessingGameServer is the server API for GuessingGame service.
// All implementations must embed UnimplementedGuessingGameServer
// for forward compatibility
type GuessingGameServer interface {
	MakeGuess(context.Context, *Guess) (*GuessResult, error)
	mustEmbedUnimplementedGuessingGameServer()
}

// UnimplementedGuessingGameServer must be embedded to have forward compatible implementations.
type UnimplementedGuessingGameServer struct {
}

func (UnimplementedGuessingGameServer) MakeGuess(context.Context, *Guess) (*GuessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeGuess not implemented")
}
func (UnimplementedGuessingGameServer) mustEmbedUnimplementedGuessingGameServer() {}

// UnsafeGuessingGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuessingGameServer will
// result in compilation errors.
type UnsafeGuessingGameServer interface {
	mustEmbedUnimplementedGuessingGameServer()
}

func RegisterGuessingGameServer(s grpc.ServiceRegistrar, srv GuessingGameServer) {
	s.RegisterService(&GuessingGame_ServiceDesc, srv)
}

func _GuessingGame_MakeGuess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Guess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuessingGameServer).MakeGuess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuessingGame/MakeGuess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuessingGameServer).MakeGuess(ctx, req.(*Guess))
	}
	return interceptor(ctx, in, info, handler)
}

// GuessingGame_ServiceDesc is the grpc.ServiceDesc for GuessingGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuessingGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GuessingGame",
	HandlerType: (*GuessingGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeGuess",
			Handler:    _GuessingGame_MakeGuess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/guessing-game.proto",
}
